init:
  - git config --global core.autocrlf true

shallow_clone: true

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.11'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run-script pretest

build: off

test_script:
  - ps: 'npm run-script test-only # PowerShell'
  - cmd: npm run-script test-only

cache:
  - bower_components
  - node_modules
