init:
  - git config --global core.autocrlf true

shallow_clone: true

version: '{build}'

skip_tags: true

environment:
  matrix:
    - nodejs_version: '1'
    - nodejs_version: '0'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install bower each-exec require-bower-files tape
  - npm run-script pretest

build: off

test_script:
  - ps: 'npm run-script test-only # PowerShell'
  - cmd: npm run-script test-only

cache:
  - bower_components
  - node_modules
